### ISSUE TITLE
当用户传递的activeRule为字符串。应使用 location.hash === path

### ISSUE THREAD

**Issue by buluohe** [woai3c/mini-single-spa#1]
项目 v1版本，registerApplication.ts =》第八行 =》修改为  app.activeRule = (location = window.location) => location.hash === path

**Comment by woai3c** [comment]
> 项目 v1版本，registerApplication.ts =》第八行 =》修改为 app.activeRule = (location = window.location) => location.hash === path

以路径为主，hash 可以自己写个函数.

**Comment by buluohe** [comment]
好的
